### PR TITLE
Drop mime-types dependency. It works fine in Rails 4.

### PR DESCRIPTION
**Pull request by p0deje**
@jarmo Please, take a look

### CODE REVIEW

**Comment by jarmo** [comment]
(y)

You can release a `1.1.0` or is it `1.0.5` if trying to follow Semantic Versioning?

**Comment by p0deje** [comment]
> You can release a 1.1.0 or is it 1.0.5 if trying to follow Semantic Versioning?

Good question. Guess it's better to do 1.1.0 release. I'll do that.

**Comment by p0deje** [comment]
@jarmo I've pushed commit/tag but I don't have access to watir-rails on Rubygems. Can you add me `gem owner watir-rails --add p0deje@gmail.com` or release by yourslef?

**Comment by jarmo** [comment]
Done!

**Comment by p0deje** [comment]
Thanks!

**Pull request merged**
