### PR TITLE
Fixed deprecation warnings

### PR DESCRIPTION
**Pull request by jasnow**
I fixed all of the deprecation warnings during a **rake spec** run.l

### CODE REVIEW

**Comment by jasnow** [comment]
Broken Travis so deleting the pull request for the time being.

**Comment by jarmo** [comment]
I don't think that your changes broke Travis. It's broken with `master` as well and i cannot reproduce that problem on my OS X with the same Ruby version...

**Comment by jasnow** [comment]
I upgraded rspec to 3.x (to fix my previous errors) rand got the
specs to run green (except 2 lines). Here is my Travis green run:
https://travis-ci.org/jasnow/watir-rails/builds/52633800

Can you please help me with fixing the 2 commented "FIXME:"
lines (14 and 31) in watir-rails/spec/watir/rails_spec.rb?

Here is my repo: https://github.com/jasnow/watir-rails

Thanks.

**Comment by jarmo** [comment]
Are they same errors at with the official build here?
https://travis-ci.org/watir/watir-rails/builds/52527701

J.

**Comment by jasnow** [comment]
@jarmo - Finally found your above comment. The answer: Look familar. I created a new pull request and will watch Travis build. Feel free to comment in the pull request or email me if you have questions/suggestions/feedback.

**Pull request closed without merging**
